/**
 * Auto-generated by Supabase CLI. DO NOT EDIT MANUALLY.
 * Regenerate with: `npm run db:types`
 *
 * Phase 0: stub. After `supabase db push` succeeds, run db:types to populate.
 */

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
